"""MARC relator-term -> relator-code translation table, used by the 100
(personal author) field. 700 (added personal name / contributor) has its
own much smaller, distinct literal-string table -- see
``datafields/f700.py`` -- so it isn't shared here.
"""

from .prefixes import IISG_REL, RELATOR

RELATOR_TABLE = {
    "artist.": RELATOR.art,
    "auteur.": RELATOR.aut,
    "author,": RELATOR.aut,
    "author.": RELATOR.aut,
    "bibliographic antecedent.": RELATOR.bibl,
    "collector.": RELATOR.col,
    "composer.": RELATOR.com,
    "contributer.": RELATOR.ctb,
    "creator.": RELATOR.cre,
    "designer.": RELATOR.dsr,
    "director.": RELATOR.drt,
    "Director.": RELATOR.drt,
    "draughtsman,": RELATOR.drm,
    "draughtsman.": RELATOR.drm,
    "editor of compilation.": RELATOR.edc,
    "editor.": RELATOR.edt,
    "engraver.": RELATOR.egr,
    "illustrator.": RELATOR.ill,
    "interviewer.": RELATOR.ivr,
    "ontwerper.": RELATOR.dsr,
    "organizer.": RELATOR.orm,
    "painter.": IISG_REL.painter,
    "photographer.": RELATOR.pht,
    "Photographer.": RELATOR.pht,
    "photopgrapher.": RELATOR.pht,
    "phtographer.": RELATOR.pht,
    "red.": RELATOR.edt,
    "red": RELATOR.edt,
    "researcher.": RELATOR.res,
    "sculptor.": RELATOR.scl,
    "singer.": RELATOR.sin,
    "speaker.": RELATOR.spk,
    "Verfasser.": RELATOR.ver,
    "writer.": RELATOR.wrt,
    "writer": RELATOR.wrt,
    "writer of afterword.": RELATOR.aft,
    "artist": RELATOR.art,
    "auhor": RELATOR.aut,
    "auteur": RELATOR.aut,
    "authoir": RELATOR.aut,
    "author": RELATOR.aut,
    "autor": RELATOR.aut,
    "Autor": RELATOR.aut,
    "bibliographicantecedent": RELATOR.bibl,
    "cartographer": RELATOR.cart,
    "cartoonist": RELATOR.car,
    "collector": RELATOR.col,
    "comicartist": RELATOR.comc,
    "compiler": RELATOR.cor,
    "composer": RELATOR.com,
    "copyrightholder": RELATOR.copr,
    "correspondent": RELATOR.corr,
    "curator": RELATOR.cur,
    "designer": RELATOR.dsr,
    "designers": RELATOR.dsr,
    "design": RELATOR.dsr,
    "director": RELATOR.dir,
    "Director": RELATOR.dir,
    "dissertant": RELATOR.dis,
    "draeughtsman": RELATOR.drm,
    "draughstman": RELATOR.drm,
    "draughtman": RELATOR.drm,
    "draughtsman": RELATOR.drm,
    "editor": RELATOR.edt,
    "engraver": RELATOR.egr,
    "filmdirector": RELATOR.fdir,
    "fotograaf": RELATOR.pht,
    "hui": RELATOR.hui,
    "illustrator": RELATOR.ill,
    "interviewee": RELATOR.ivr,
    "interviewer": RELATOR.ivr,
    "MounaguruChitralekha": RELATOR.gur,
    "musician": RELATOR.mus,
    "ontwerper": RELATOR.dsr,
    "painter": IISG_REL.painter,
    "photogr": RELATOR.pht,
    "photographer": RELATOR.pht,
    "Photographer": RELATOR.pht,
    "photopgrapher": RELATOR.pht,
    "researcher": RELATOR.res,
    "sculptor": RELATOR.scl,
    "singer": RELATOR.sin,
    "translator": RELATOR.trn,
    "Verfasser": RELATOR.ver,
    "VerfasserIn": RELATOR.ver,
}

# `nulls` in the original translateAll config: these values must not be
# mapped (i.e. produce no relator triple at all).
RELATOR_NULLS = {"Unknown"}
